### ISSUE TITLE
Manually test that radioState returns the right values on Lollipop/Marshmallow devices that don't have the right BLE hardware

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#456] opened 2016-01-15 17:57 UTC

**Comment by vjrantal** [comment] 2016-01-17 10:41
@tompaana: I think currently, if you try to run some Thali test app on a device that doesn't have the required HW capabilities, there is an exception like https://gist.github.com/vjrantal/cd12b6246562586abdf5 .

**Comment by tompaana** [comment] 2016-02-23 15:47
This should already be fixed. Can you, @vjrantal, reproduce this?

**Comment by vjrantal** [comment] 2016-02-23 16:06
@tompaana: I am not sure since the CI was the best place to check issues like this with various devices, but we don't currently have that option. I am fine closing this and reopening if I run into this in the future.

**Closed** 2016-08-23 22:41 UTC
Labels: 1 - Backlog, estimate - 2
