### ISSUE TITLE
The device stops sending its changes to other devices after turning WiFi on and off

### ISSUE THREAD

**Issue by larryonoff** [thaliproject/Thali_CordovaPlugin#1356] opened 2016-10-18 12:33 UTC
This issue was found by @czyzm.

The issue happens on different devices when turning WiFi on and off. The result is that the device is stopping sending its changes to other devices (it is still getting changes from other devices). Here is the gist with logs from Samsung S6: https://gist.github.com/czyzm/416c5cfa05aa0f99d6f7efb15869debc.

The scenario was as follows (this scenario is not deterministic, but in most cases I get this issue):
1. Start Thali in Stanton on 2 devices (one of them is S6).
2. Turn WiFi OFF on S6.
3. Turn WiFi OFF on second device.
4. Turn WiFi ON on second device.
5. Turn WiFi ON on S6.
6. Try sending and receiving changes (sending not working, receiving ok)
   The log for steps 2-6 is named S6 in gist.

Stopping Thali doesn't work since it doesn't finish, state of ThaliManager was 'stopping' all the time.
Also starting again doesn't work (recreation of ThaliManager and calling start) - state was 'starting' all the time.
Logcat from starting and stopping are S6_called_start and S6_called_stop.

Interesting logentry could be:
`
thaliSendNotificationBasedOnReplication: 'We must have stopped because we are complete -{"status":"cancelled"}'
`

**Comment by larryonoff** [comment] 2016-10-20 10:10
additional feedback from @czyzm below

> I managed to repeat the WiFi issue in the ThaliTestApp. I have upgraded the app so that now you can select the mode you want to work with, you can have one app for both devices (you initialize Thali for each device from device using different set of ECDH keys), you can start and stop thali from the app and finally you can add data to local db and see the local db changes right in the app. 
> Note that it is not bullet proof so use with care :slightly_smiling_face:
> One issue I am observing on my side is that in order to use WiFi mode I need to first start Native mode, close app and then when started again WiFi works, otherwise I am getting 'Could not establish TCP connection'. I didn't investigate it deeper since it is not stopping us from using it.

**Comment by czyzm** [comment] 2016-10-20 11:49
Can be reproduced using ThaliTestApp: https://github.com/czyzm/ThaliTestApp

**Comment by andrew-aladev** [comment] 2016-10-21 14:23
This issue is not related with WiFi. I've prepared a 100% guaranteed test that will reproduce this issue. It sits in [aaladev_1356](https://github.com/thaliproject/Thali_CordovaPlugin/blob/aaladev_1356/test/www/jxcore/bv_tests/testThaliManagerCoordinated.js#L309)

```
jx runCoordinatedTests.js --filter=bv_tests/testThaliManagerCoordinated.js | grep -P "infinite loop|data for index|received data for"
```

Test will hangs after 15-50 attempts.

**Comment by andrew-aladev** [comment] 2016-10-21 15:31
This is not related with wifi. I've created a test that have 100% guaranteed to reproduce this hang in aaladev_1356.

Please use 2 separated terminal screens (screee/tmux screens) for this issue. One screen will see logs:
```
tail -f -n 0 /tmp/fit.txt | grep -P "infinite loop|data for"
```
Other will run test:
```
jx runCoordinatedTests.js --filter=bv_tests/testThaliManagerCoordinated.js > /tmp/fit.txt
```

WARNING `socket.io` with `websocket` is not reliable even on loopback! You have a 0.001% chance to receive [such log](https://gist.githubusercontent.com/andrew-aladev/babd402d8d805b5a359a42495a6912d2/raw/f056f5ab0fc0fb212b66efc27caef28eaacacf93/gistfile1.txt). Just ignore it.

So the typical bug that we have is:
```
1 client: sending data for index: 63
1 client: waiting data for index: 63
1 client: received data for old remote doc
1 client: received data for old remote doc
1 client: received data for local doc
2 client: sending data for index: 63
3 client: sending data for index: 63
2 client: waiting data for index: 63
3 client: waiting data for index: 63
3 client: received data for old remote doc
3 client: received data for old remote doc
3 client: received data for local doc
2 client: received data for old remote doc
2 client: received data for old remote doc
2 client: received data for local doc
2 client: received data for new remote doc
3 client: received data for new remote doc
```

**Comment by andrew-aladev** [comment] 2016-10-21 21:06
We've found a big bug here. `jxcore v8` throws a `SIGSEGV` both on linux and osx. `jxcore sm` throws `uncaught promise rejection, error: 'Error: read ECONNRESET'` and `uncaught promise rejection, error: 'Error: connect EMFILE'`.

So `socket.io` with `websocket` failed on loopback network because of segfault. We were loosing documents because of segfault and uncaught exception. We need to ask @enricogior for help.

**Comment by yaronyg** [comment] 2016-10-21 21:36
BTW I looked at the original log and it just shows that PouchDB thinks that it's done pulling in changes. But @czyzm against we HAVE to have both logs from both devices! We can't debug anything with just one side of the logs.

**Comment by yaronyg** [comment] 2016-10-21 21:50
Oh and @czyzm it's important I think to understand how we move changes around using PouchDB. We only use what is called pull replication. This means that A will pull changes from B. So if A is connected to B but B is NOT connected to A then A will see any changes on B but B won't see any changes on A. 

So in the example above where you said that S6 could see the changes on the S7 (I'm just calling the other phone S7 to give it a different name than the S6) but the S7 couldn't see the changes on the S6 what this means is that the S6 was successfully replicating with the S7 and it was the S7, not the S6 that had the bug. In other words, we have the wrong log above to even diagnose the problem! Again, this is why when filing bugs you have to always give us all the logs of all the devices.

**Comment by andrew-aladev** [comment] 2016-10-21 23:47
I was wrong. Another test attempt shows that jxcore with spider monkey can provide a SIGSEGV. Maybe this issue become more important for @enricogior.

**Comment by yaronyg** [comment] 2016-10-22 01:12
@andrew-aladev please check out aaladev_1356_yarong. I wrote a stripped down version of the test that does exactly what your original version does but without any of the previous tests having to run first. This let me discover some interesting things. One of which is that we sync on Wifi on the desktop just fine. 

The issue is waitForRemoteDocs.allDocsFound. It insists on finding both the new and old docs. Under very controlled circumstances that is o.k. but in the rough and tumble of multiple rounds it stops working. All we actually have to validate in this specific case is that we get the new docs.

When I ran the test I got through 74 rounds before the 3 minute timer was up. But that was using Spider Monkey. If I ran the test using V8 then I would get through 52 rounds before one of the images would segfault.

But a big change I made to aaladev_1356_yarong is that I used the thaliPeerPoolOneAtATime.js policy manager, not the default one.

So please do the following:
1.Please go to https://github.com/czyzm/ThaliTestApp and see if you can manually cause it to reproduce the behavior that @czyzm saw.
2. Once you get it to repro then please modify https://github.com/czyzm/ThaliTestApp to use thaliPeerPoolOneAtATime.js from master_1274_trivial and see if you can still repro.
3. If you can still repro then please modify aaladev_1356_yarong to start and stop the thaliManager (NOT WIFI) and see if you can get it to behave badly. If so, please fix! :) If not THEN try to start and stop wifi.

**Comment by czyzm** [comment] 2016-10-24 09:33
Here are the logs from this issue from ThaliTestApp using new peer pool (OneAtATime) from master_1274_trivial. Note that ThaliTestApp was locally modified to use the new peer pool. Additionally I needed to merge master_fix-install into master_1274_trivial in order to build the app.

I used 2 devices - Nexus 6P and S7. After turning off and on WiFi on S7 I tried adding data on Nexus and on S7. Data add on Nexus is visible on S7, data added on S7 i not visible on Nexus.

Logs:
[Nexus](https://gist.github.com/czyzm/432f6e594e91cf591d05f790bc5c0216)
[S7](https://gist.github.com/czyzm/6a49abc9b5b0c0eb28d5999cccee0c77)

**Comment by andrew-aladev** [comment] 2016-10-24 10:32
Yes, this test is the same, we can ignore old documents. I've added cosmetics here. We can reproduce bug in `aaladev_1356_yarong`.

```
jx runCoordinatedTests.js --filter=bv_tests/testThaliManagerCoordinated.js | grep -P "data for|sync ok|SIG|uncaught"
```

On `jxcore + v8` = always segfault + caught exception. On `jxcore + sm` = uncaught exception/caught exception with segfault or without it. What type of exceptions?

```
read ECONNRESET
connect EMFILE
```

On `jxcore + sm` you will receive an exception with 95% chance, segfault with 5% chance. Please run this test many-many times and you will definitely receive a segfault. I've got 1 segfault per 40 attempts, but I am sure that it appears.

**Comment by czyzm** [comment] 2016-10-24 10:33
And here are the logs from iOS devices using Stanton and new peer pool (OneAtATime) from master_1274_trivial. 

I used 2 devices (Thali54 and Thali56). I turned WiFi off and on on Thali54 -  after that replication was working. Then I turned WiFi off (Thali54), sent a message and turned WiFi on (Thali54). After that messages sent from Thali54 are not delivered to Thali56, while messages sent from Thali56 are delivered to Thali54. When I sent message from Thali54 I see in the logs: thaliSendNotificationBasedOnReplication: 'We must have stopped because we are complete -{"status":"cancelled"}'

Logs:
[Thali54](https://gist.github.com/czyzm/538122c04a8ff908e61bd291ae787434)
[Thali56](https://gist.github.com/czyzm/71566f20e7293a309f2e9b9e8a095015)

**Comment by andrew-aladev** [comment] 2016-10-24 11:57
@czyzm, I've just got 2 same htc phones and it works in wifi mode without problems.

What I am doing?

1. In application press `WiFi` button (`Native` button is not active) for each phone.
2. Press `Init Thali #1`, `Init Thali #2` and `Start Thali` buttons for each phone.
3. Press `Add data` on the first phone. This data is displayed on both phones. It works.

4. Disable wifi for each phone, wait 1 minute, enable wifi for each phone.
5. Press `Add data` on the first phone. This data is displayed on both phones.
6. Press `Add data` on the seconds phone. This data is displayed on both phones. It works fine.

**Comment by andrew-aladev** [comment] 2016-10-24 12:37
Suddenly application stopped working after new deploy both with `ThaliPeerPoolDefault` and `ThaliPeerPoolOneAtATime`.

**Comment by andrew-aladev** [comment] 2016-10-24 13:20
I definitely know how to make this application works perfect without bugs!

1. In application press `WiFi` button (Native button is not active) for each phone.
2. Press `Init Thali #1` and `Start Thali` for each phone and wait about 10 seconds.
3. Press `Init Thali #2` and `Start Thali` for each phone.
3. Press `Add data` on any phone in any mode (online/offline) and data will be replicated.

**Comment by larryonoff** [comment] 2016-10-24 14:51
@czyzm posted logs that may have the same issue that we're having in this issue but in Native mode

> Did tests in native mode (with new peer policy). Good news is that I don't see any performance 

> issues. Bad is that it stops working sometimes. It may be similar issue as the WiFi (1356) because one phone see other phones changes but not the other way. Here are logs of the Stanton run on S7 and Nexus. I sent message from S7, then from Nexus and repeated the same once again. Messages sent from S7 are delivered to Nexus, but messages sent from Nexus are not delivered to S7.
> 
> S7 logs: https://gist.github.com/czyzm/5a1a916c25dfe9156005ce87e0cce1c8
> Nexus logs: https://gist.github.com/czyzm/25b92d6ed662d5cb838e64eaedfdc2f9

**Comment by andrew-aladev** [comment] 2016-10-24 17:04
@czyzm We are receiving uncaught promise rejection 409 conflict and application crashes. Please change `add data`:

```
Mobile('addData').registerSync(function (data) {  
    var time = process.hrtime();
    var doc = {
        "_id": "TestDoc-" + (time[0] + time[1] / 1e9),
        "content": "[" + myDeviceId + "] " + data
    };
    localDB.put(doc);
});
```

**Comment by andrew-aladev** [comment] 2016-10-24 17:19
I've just figured out another the reason for application to crash if we are toggling wifi too often.

```
uncaught promise rejection, error: 'AssertionError: Attempting to clear a non-existing interval'
process exited, code: '2', signal: 'undefined'
```

**Comment by andrew-aladev** [comment] 2016-10-24 17:30
I've received a crash without any logs. I was working with `logcat` without filters.
```
...
DEBUG thaliManager: 'connected pskIdentity mdGBbQROMLxruFFD312U75hWHSVyZcNpbR6jr4JnO3I for path /db/testdb/_local/pIEo5gMc0PL3U21Hw5aHbw%3D%3D'
10-24 20:26:27.926  3473  4335 D GraphicsStats: Buffer count: 7
10-24 20:26:27.926  3473  4587 I WindowState: WIN DEATH: Window{2d2bf93 u0 d0 com.example.ThaliTestApp/com.example.ThaliTestApp.MainActivity}
10-24 20:26:27.926  3473  4107 D ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ id=122, legacyType=-1, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED] ], android.os.BinderProxy@d7ab383)
```

**Comment by yaronyg** [comment] 2016-10-24 21:46
@andrew-aladev Please fix the data bug. I filed #1412 on the second issue and #1413 on the third issue. But per our conversation today there clearly is still a bug where we aren't advertising beacons when we should be. So please follow that up.

**Comment by czyzm** [comment] 2016-10-25 10:00
@andrew-aladev ThaliTestApp is fixed (added catch for db.put). I also changed peer pool to the OneAtATime so it must be used now with master_1274_trivial. You should change it to default if you want.

**Comment by larryonoff** [comment] 2016-10-25 10:10
@czyzm please also add `../../../Thali_CordovaPlugin/thali/install/setUpDesktop.sh` in `prepare.sh` as it mentioned in the latest README (just updated it).

**Comment by andrew-aladev** [comment] 2016-10-25 13:25
I've found the reason of this issue. Multicast address just stopped working. Our ssdp server is sending client's data each 0.5 seconds and receives this client's data only. It couldn't receive another client's data. I will provide a simplified test for @enricogior.

**Comment by andrew-aladev** [comment] 2016-10-25 14:26
I've created a [simplified `app.js`](https://gist.github.com/andrew-aladev/18fb365e3934b1e71d030bdec1ac09f5) for @enricogior. I've launched it on 2 desktops and 2 mobile devices in the same subnet. Desktop versions works perfect, mobile versions does nothing, it can't receive any message.

**Comment by yaronyg** [comment] 2016-10-25 15:03
@enricogior Does this occur only if we turn wifi on and off or does this bug also occur if we have wifi on but don't have a base station (we are out of range)?

**Comment by enricogior** [comment] 2016-10-25 17:31
I first tried to repro the issue using the jxcore standalone for android using a Galaxy S6 and a Galaxy S7: the bug doesn't repro, I tried all sort of combination turning the WiFi on and off on both devices, no problems.
I will now create my own cordova test app instead of using the modified thali test app.

**Comment by yaronyg** [comment] 2016-10-25 18:43
@enricogior please feel free to pull in @andrew-aladev as needed. But I would think the easiest thing to do is to create a cordova app using the readme and just shove in the app.js and make sure you install node-uuid.

**Comment by enricogior** [comment] 2016-10-25 19:16
I've created the cordova app, installed it on the two devices and it worked without problems.
Turning the WiFi off, stops the data to be sent/received, but about 1-2 seconds after the WiFi is on again the data starts been sent/received again.
This time I've also run the script on the desktop.
I also tested putting one device out of the router reach and, when it got the signal back, it started sending/receiving again. I used a home made faraday's cage that allows to lower the WiFi signal at will, so I also tested with the device running with a very weak wifi signal, some packets were lost intermittently but not causing a unrecoverable problem.

**Comment by andrew-aladev** [comment] 2016-10-25 20:54
This is strange, we reproduced this issue easily on htc, samsung and nexus. Please try to press `add data` button very often in offline and online state on both devices.

**Comment by yaronyg** [comment] 2016-10-26 15:45
Note that we enabled some tests in testThaliMobile that turn radios on and off and they fail at a minimum because our logic that allows us to reconnect to the connection server fails. That logic is just connecting to an IP and port and so should work fine across wifi being turned off. It is interesting that there would have been an open IP connection when wifi was turned off. In iOS at least that is a bad thing so we need to investigate in Android if having open connections when wifi turns off somehow screws up libuv.

BTW the specific tests:
* when network connection is lost a peer should be marked unavailable'
* 'network changes emitted correctly'
* 'network changes not emitted in stopped state',

**Comment by andrew-aladev** [comment] 2016-10-26 16:09
We've finally found the problem. Our local wifi network blocks multicast sometimes. I've created a new wifi access point without any security rules, without any authentication and I couldn't reproduce this issue again. I've tried at least 100 wifi toggles. @czyzm Please create a new wifi access point and try again.

**Comment by yaronyg** [comment] 2016-10-26 16:10
We have confirmed that some routers appear to get seriously unhappy if you use a multicast address, disconnect, reconnect and try to use the same multicast address. they will block the re-use of the address and break us completely. There is nothing we can do.

But we have seen a unicast variant of this bug where when we run the tests above we can't reconnect to the coordination server and that is a unicast connection.

**Comment by enricogior** [comment] 2016-10-26 16:14
The router I'm using is Asus RT-AC68U with WPA2-Personal and 5.0 Ghz antenna.

**Comment by enricogior** [comment] 2016-10-27 14:04
I can't repro the problem:
https://gist.github.com/enricogior/80cdf749cc2de39d2f1a86e094d71e87

After the wifi is turned back on, the device reconnects to the server:
```
2016-10-27 13:42:37 - DEBUG HttpServer: 'device presented, name: 'samsung-SM-G925F', uuid: 'f9c161e2-8232-4891-a1dc-acc93a464795', platformName: 'android', type: 'unittest', hasRequiredHardware: 'true', nativeUTFailed: 'false''
2016-10-27 13:42:37 - INFO TestFramework: 'updating existing device, name: 'samsung-SM-G925F', uuid: 'f9c161e2-8232-4891-a1dc-acc93a464795', platformName: 'android''
```

**Comment by yaronyg** [comment] 2016-10-27 14:45
It seems like this is a problem with the router, we need to figure out how to get a router for minsk that doesn't have these issues. We also need to understand why the reconnect logic isn't working for coordination.

**Comment by czyzm** [comment] 2016-10-28 04:49
I tried with ThaliTestApp and WiFi network created on my Mac and still can see the same issue - for both turning on/off WiFi and loosing connection. I assume it may be connected with #1431 .

The main router for our tests is TP Link TL-WR1043ND (the same as used in CI).

**Comment by yaronyg** [comment] 2016-10-28 16:38
The PR for #1431 has been submitted. It should be checked in on Monday morning assuming no issues so please retry. This is one bug we need to squash quickly.

**Comment by czyzm** [comment] 2017-02-15 06:57
Checked with ThaliTestApp. Issue no longer visible. Closing

**Closed by czyzm** 2017-02-15 06:57 UTC
Labels: bug
