### ISSUE TITLE
Implement Node.js TLS extension for PSK

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#247] opened 2015-10-27 14:56 UTC

**Comment by cicorias** [comment] 2015-12-02 15:46
Is this a duplicate of #329 ?

**Comment by yaronyg** [comment] 2015-12-02 17:17
Not so much a duplicate as the parent issue.

**Comment by cicorias** [comment] 2016-01-14 18:54
@yaronyg if this is a parent of other items, then this should be 0

**Comment by yaronyg** [comment] 2016-01-14 18:57
We typically don't have parent bugs. So I would argue that #247 and #329 are dupes of each other.

**Comment by cicorias** [comment] 2016-01-15 15:20
closing as duplicate of #329

**Closed by cicorias** 2016-01-15 15:20 UTC
Labels: 4 - Done, estimate - 5, ready
