### ISSUE TITLE
'#_doImmediateSeqUpdate - update seq three times' - We are getting an error in lie

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#1237] opened 2016-10-03 16:11 UTC
Repro - Run this file 6 times and it will blow up, it will give us a proper error and then lie will fail out. We need to know why.

**Comment by yaronyg** [comment] 2016-10-03 16:12
After I repro this I need to see if replacing lie with bluebird fixes it.

**Comment by enricogior** [comment] 2016-10-03 16:12
```
not ok 178 Got error - {"code":"EMFILE","errno":"EMFILE","syscall":"connect"}

  ---
operator: fail
at: Array.0 (/Users/enrico/thali/Thali_CordovaPlugin/test/www/jxcore/node_modules/lie/lib/index.js:88:21)
  ...
```

**Comment by yaronyg** [comment] 2016-10-03 21:13
So I just ran the file 10 times using jxcore v0.3.1.4  with Google V8 v3.14.5.9 and I didn't get an error. :( In fact, I ran it 3 passes, each pass ran 10 times. No errors. Just to be clear the file I ran was testLocalSeqManager.js.

Just to be paranoid I deleted all of my node_modules and re-ran thali/install/jx npm run setupDesktop. I then ran the test again. It passed. Just for fun I ran it 30 times in a row and yes, it passed.

Now my suggestion to you guys is - delete every node_modules directory you have in Thali_CordovaPlugin and run 'thali/install/jx npm run setupDesktop' again. The reason is that I have seen in the past spurious errors kind of like this happen when node_modules get into a weird state. Although to be honest when I've seen these kinds of errors they happen immediately, not after 6 runs. So I am worried.

It's worth pointing out that when you switch from mobile to desktop you MUST run the setup scripts again. In other words if you have recently run 'jx npm run setupDesktop' and then you want to switch to creating ThaliTest so you can run on a device then you need to run 'jx npm run setupUnit'. And if you then switch back from cordova to desktop then you have to run 'jx npm run setupDesktop' again. And so on and so forth. I usually delete all the node_modules directories in between running those two scripts just to be super duper paranoid.

As one last desperate bid I ran just the failing test 100 times and it passed no problem.

I published my test at https://github.com/thaliproject/thali_cordovaplugin/tree/master_1237. I ran the test via 'jx runTests.js bv_tests/testLocalSeqManager.js'

Please let me know if it still repo's on your machine.

**Comment by enricogior** [comment] 2016-10-05 13:15
@yaronyg in order to repro the problem, please use jxcore with SpiderMonkey.

**Comment by enricogior** [comment] 2016-10-07 14:01
Repro steps using current 'master' branch:
 1 - in test/www/jxcore/bv_tests remove all tests but testLocalSeqManager.js
 2 - create 6 more copies of the testLocalSeqManager.js
 3 - from test/www/jxcore run `jx runCoordinatedTests.js`

With both V8 and SM the result is that all three instances of the jxcore will failt with the `operator: fail` error message.
It repros with both jxcore 3.1.4 and 3.1.5.

**Comment by yaronyg** [comment] 2016-10-07 21:30
@enricogior In the future why not just commit your test somewhere so I can look at it? Having me try to reproduce things from your instructions leaves too many places for things to go wrong.

But in any case I tried to repro with the latest master. I'm still on 3.1.4 and I couldn't repro.

So I decided to change things up and instead of running the tests 10 times in the file I did what you said above and I replicated the file testLocalSeqManager.js 6 times and moved all the other tests out so they wouldn't run. 

Now I do get 'operator: fail' but that's actually just fine. As long as you get the 'operator: fail' as part of the body of a 'not ok' then you are fine. This is saying that the test failed. Not for any particularly bad reason but because we called t.ok() with a failing value.

In other words, even the error log at the start of the bug is only a problem because we shouldn't have gotten an enfile error but the lie 88:21 is perfectly normal!

I have updated the branch I linked to above (master_1237) to match exactly what you describe and when I run it I do get test failures.

For example, I have a test 'do we cancel timer properly on an immediate' where I call update, wait for it to return and then immediately call update again. What I want to see is that the second update doesn't fire immediately because not enough time has passed since the first update. But if the system gets backed up and swaps out for a bit and then comes back then by the time the second update fires enough time HAS passed to allow a second update and BOOM, test fails because it was expecting that second update not to run immediately. Ooops.

Fixing this is a colossal pain and not worth it right now. But I have filed thaliproject/Thali_CordovaPlugin#1276 to get to it someday.

Given this, do we still have a bug here?

**Comment by yaronyg** [comment] 2016-10-07 21:35
Oh and I updated the branch because it turns out I had reproduced the file where I run the test 10 times, 6 times for a total of 60 runs. That would reliably fail. But I 'fixed' it so that each file runs the tests once and I have 6 files for a total of 6 runs and that actually passes.

**Comment by enricogior** [comment] 2016-10-10 12:54
@yaronyg 
next time I'll provide a branch with everything set up, sorry for not having done it in the first place.
I assumed the 'operator: fail' message was not expected, but if you say it's ok to get that message we can close the issue since it's not a bug.
Thank you.

**Closed** 2016-10-10 14:33 UTC
