### ISSUE TITLE
Android native does not call callback of the Mobile('connect')

### ISSUE THREAD

**Issue by chapko** [thaliproject/Thali_CordovaPlugin#1583] opened 2016-11-30 12:24 UTC
Test: 'Can connect to a remote peer' from testThaliMobileNative.js
Branch: `master` (da2e96f7eccbd9dbd6362037dc39182abd551c4c)

See logs:
- [ENU7N15B26000497.log](https://gist.github.com/chapko/1d589e6e563788895228efe3960e0d7a/raw/9450429bfb648e0dcabcfb1317206d66268b65a0/ENU7N15B26000497.log)
- [ENU7N16425000183.log](https://gist.github.com/chapko/1d589e6e563788895228efe3960e0d7a/raw/9450429bfb648e0dcabcfb1317206d66268b65a0/ENU7N16425000183.log)
- [ENU7N16425000206.log](https://gist.github.com/chapko/1d589e6e563788895228efe3960e0d7a/raw/9450429bfb648e0dcabcfb1317206d66268b65a0/ENU7N16425000206.log)

After 
```
INFO testThaliMobileNative: 'Received peerAvailabilityChanged with peers:
```
log node tries to connect to the discovered peer. After that you should either see 
```
INFO testThaliMobileNative:
```
with returned connection info or error description.
But there are no jxcore logs for ~3 min

**Comment by evabishchevich** [comment] 2016-11-30 12:38
@chapko  I can't build master. There are some problems with tets

https://gist.github.com/evabishchevich/859a397f3d309bd77c599055bf16a418

**Comment by vasilevskayaem** [comment] 2016-12-01 14:35
closed as duplicate of thaliproject/Thali_CordovaPlugin#1588

**Closed** 2016-12-01 14:36 UTC
Labels: Android, bug
