### ISSUE TITLE
Get perf tests for iOS running in CI

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#153] opened 2015-10-13 15:29 UTC
See #152

**Comment by yaronyg** [comment] 2015-10-20 15:05
10/20 - We can't currently deploy to iOS and we think it's a time out because of the size of our tests. But we can't see what is going on because the logs aren't visible yet. So we are blocked until that is fixed.

**Comment by yaronyg** [comment] 2015-10-22 15:15
10/22 - He is really looking at iOS all up, not just perf tests.

**Comment by vjrantal** [comment] 2015-10-23 12:28
This is pretty much a duplicate of https://github.com/thaliproject/Thali_CordovaPlugin/issues/189 so closing this and keeping the other up-to-date on progress.

**Closed by vjrantal** 2015-10-23 12:28 UTC
Labels: in progress
