### ISSUE TITLE
"test repeat write 1" fails on iOS in WiFi mode

### ISSUE THREAD

**Issue by dersim-davaod** [thaliproject/Thali_CordovaPlugin#1782] opened 2017-02-08 17:53 UTC
```
2017-02-08 17:24:49 - DEBUG UnitTestFramework: '#run: 'test repeat write 1''
2017-02-08 17:27:49 - ERROR UnitTestFramework: '#run failed: 'test repeat write 1', error: 'TimeoutError: timeout exceeded, event: 'run_test repeat write 1_finished', test: 'test repeat write 1'', stack: 'TimeoutError: timeout exceeded, event: 'run_test repeat write 1_finished', test: 'test repeat write 1'
    at afterTimeout (/Volumes/Macintosh_HD/work/Thali/Thali_CordovaPlugin/test/TestServer/node_modules/bluebird/js/release/timers.js:49:15)
    at timeoutTimeout [as _onTimeout] (/Volumes/Macintosh_HD/work/Thali/Thali_CordovaPlugin/test/TestServer/node_modules/bluebird/js/release/timers.js:76:13)
    at Timer.listOnTimeout [as ontimeout] (timers.js:120:15)''
2017-02-08 17:27:49 - ERROR UnitTestFramework: 'failed to run unit tests, platformName: 'ios', error: 'TimeoutError: timeout exceeded, event: 'run_test repeat write 1_finished', test: 'test repeat write 1'', stack: 'TimeoutError: timeout exceeded, event: 'run_test repeat write 1_finished', test: 'test repeat write 1'
    at afterTimeout (/Volumes/Macintosh_HD/work/Thali/Thali_CordovaPlugin/test/TestServer/node_modules/bluebird/js/release/timers.js:49:15)
    at timeoutTimeout [as _onTimeout] (/Volumes/Macintosh_HD/work/Thali/Thali_CordovaPlugin/test/TestServer/node_modules/bluebird/js/release/timers.js:76:13)
    at Timer.listOnTimeout [as ontimeout] (timers.js:120:15)''
```

logs from device is [here](https://gist.github.com/dersim-davaod/aa41ae17def4ae209b2825f52004c3c7):

**Comment by chapko** [comment] 2017-02-13 10:10
It is a duplicate of #1771

**Closed by chapko** 2017-02-13 10:10 UTC
Labels: iOS, Node
