### ISSUE TITLE
Fix test "enqueue and run in order"

### ISSUE THREAD

**Issue by evabishchevich** [thaliproject/Thali_CordovaPlugin#1734] opened 2017-01-17 09:11 UTC
Logs:
S6 https://gist.github.com/enricogior/1a597fcac133a77020be85055b3627a5
S7 https://gist.github.com/enricogior/1501f3c9d2352b2ed991d2ce18ce0a55
6P https://gist.github.com/enricogior/e382b62be1177df8a0a4424a3c81e091
server https://gist.github.com/enricogior/b479162d1677ba1e6c4fdd38f5f94f31

Search for
```
ERROR pouchDBCheckpointsPlugin: 'Error while fetching db info: 'Error: ENOENT, lstat '/data/user/0/com.test.thalitest/files/pouchdb-test-directory/59ek57zqqf59ek96l05o/CURRENT'', stack: '@native:jxcore_js_object:3:12
```

branch: evabishchevich_1724
commit: https://github.com/thaliproject/Thali_CordovaPlugin/commit/a486bdc2327457fb7a6784632b1b157f1bbc2e3b

**Comment by chapko** [comment] 2017-01-18 11:24
Had the same failure on three samsung s7. Logging in this test is not informative at all, so this test probably should be updated:
- [server.log](https://gist.github.com/chapko/375cdd9dc29d1d21d474dd3bd39824ba/raw/d8f2080e822299b9da736003f16b67c83472d603/server.log)
- [SM_G930F-988667514534423146.log](https://gist.github.com/chapko/375cdd9dc29d1d21d474dd3bd39824ba/raw/d8f2080e822299b9da736003f16b67c83472d603/SM_G930F-988667514534423146.log)
- [SM_G930F-ad081603480f209327.log](https://gist.github.com/chapko/375cdd9dc29d1d21d474dd3bd39824ba/raw/d8f2080e822299b9da736003f16b67c83472d603/SM_G930F-ad081603480f209327.log)
- [SM_G930F-ad091603590587540b.log](https://gist.github.com/chapko/375cdd9dc29d1d21d474dd3bd39824ba/raw/d8f2080e822299b9da736003f16b67c83472d603/SM_G930F-ad091603590587540b.log)

Branch: `iOS_aaladev_1721`.
Commit: 97b5767f2cf4b2127fdfdc98e679b90a2dbb6686

**Comment by chapko** [comment] 2017-01-19 15:31
This is a bug in the pouchdb-size plugin. It looks like it does not officially support pouch 6 yet. I've provided a PR pouchdb/pouchdb-size#28 that makes it work with the latest PouchDB.

@yaronyg I don't know how much time it will take for this PR to be accepted and merged. So for now I am going to update our package.json to point pouchdb-size dependency to the specific commit with the fix.

**Comment by yaronyg** [comment] 2017-01-19 16:59
Seems logical. But we need to keep this bug around to notice when the PR is accepted so we can switch back.

**Comment by chapko** [comment] 2017-01-19 19:32
Well, it looks like we don't depend on the fix in the pouchdb-size, leveldown-mobile probably creates all required directories and files synchronously. I've found some race conditions in our checkpoint plugin and now I'm working on creating test cases that can reproduce these bugs.

**Closed** 2017-01-20 12:05 UTC
Labels: bug, Node
