### ISSUE TITLE
Test 'Coordinated seq test' failed on Android

### ISSUE THREAD

**Issue by evabishchevich** [thaliproject/Thali_CordovaPlugin#1182] opened 2016-09-27 13:30 UTC
'# setup
09-27 16:22:43.075 17705-17779/com.test.thalitest I/jxcore-log: # Coordinated seq test
09-27 16:22:43.235 17705-17779/com.test.thalitest I/jxcore-log: 2016-09-27 13:22:43 - DEBUG thaliWifiInfrastructure: 'listening 44237'
09-27 16:22:44.404 17705-17779/com.test.thalitest I/jxcore-log: 2016-09-27 13:22:44 - DEBUG localSeqManager: 'Got an error trying to update seq {"message":"3625998640:error:14077102:SSL routines:SSL23_GET_SERVER_HELLO:unsupported protocol:../deps/openssl/openssl/ssl/s23_clnt.c:726:\n","status":500}'
09-27 16:22:44.406 17705-17779/com.test.thalitest I/jxcore-log: 2016-09-27 13:22:44 - DEBUG testUtils: 'Got an err - Error: 3625998640:error:14077102:SSL routines:SSL23_GET_SERVER_HELLO:unsupported protocol:../deps/openssl/openssl/ssl/s23_clnt.c:726:
                                                                '
09-27 16:22:46.039 17705-17779/com.test.thalitest I/jxcore-log: ok 79 should be equal

branch : vNext_yarong_417_812_848, commit 082d05c
mode: WIFI

**Comment by evabishchevich** [comment] 2016-09-27 13:42
One more time
https://gist.github.com/evabishchevich/2f7ea080c1e6ff50d329afe8720e0cd8

Look like 1 peer  just hanged in the middle of the test

**Comment by evabishchevich** [comment] 2016-09-28 13:16
https://gist.github.com/evabishchevich/4655f7dbd55d7951d00be021ed0ff0cb

Look at the 2nd peer. 1st and 3rd got timeout error in 16:08, but the 2nd one got DEBUG CoordinatedClient: 'all tests completed' on 16:10, and error only in 16:12

branch vNext_417_812, commit: ad3a05dbe817e3bcac96be7716c8d2dc90e911ed
mode: WIFI
Test fails randomly

**Comment by evabishchevich** [comment] 2016-09-28 13:39
https://gist.github.com/evabishchevich/e888319410bac2425038fa9ff3433684

branch vNext_417_812, commit: ad3a05dbe817e3bcac96be7716c8d2dc90e911ed
mode: WIFI
Test fails randomly

**Comment by yaronyg** [comment] 2016-09-28 15:49
We are moving to get rid of buffer util is socket.io and there is some hope that might clean this up.

**Comment by larryonoff** [comment] 2016-09-29 10:00
@vasilevskayaem please check tests since `socket.io` was updated after thaliproject/Thali_CordovaPlugin#1179.

**Comment by vasilevskayaem** [comment] 2016-09-29 12:11
I ran this test 8 times separately and all tests completed successfully. Now I will check it with another tests

**Comment by vasilevskayaem** [comment] 2016-09-29 12:24
Tested Coordinated seq test with other tests 10 times, Coordinated seq test finished successfully but "test write" failed 3 times.

**Comment by larryonoff** [comment] 2016-09-29 12:30
"test write" test failures are already in thaliproject/Thali_CordovaPlugin#1165.

**Comment by vasilevskayaem** [comment] 2016-09-29 12:37
finally i get error on Coordinated seq test , log https://gist.github.com/vasilevskayaem/30d51910cc104de75430e78cc5c199fc

**Comment by vasilevskayaem** [comment] 2016-09-30 10:34
tested 15 times on master branch with "jxcore-cordova-url": "http://jxcore.azureedge.net/jxcore-cordova/0.1.4-v8/release/io.jxcore.node.jx", can't reproduce on Samsung SM-G920F, Samsung SM-G930F and Nexus 6P

**Comment by enricogior** [comment] 2016-10-06 09:08
Currently, running the tests from master, this test is skipped:
```
'skipped tests: '["Coordinated seq test","Make sure docs replicate"]''
```

**Comment by larryonoff** [comment] 2016-10-06 09:17
@enricogior yes. these tests are skipped, because they're fail.

You can un-skip **Coordinated seq test** by opening file `test/www/jxcore/bv_test/testLocalSeqManagerCoordinated.js` line 74-78, and just removing this skip function. The same can be done with **Make sure docs replicate**.

**Comment by enricogior** [comment] 2016-10-06 11:45
The test passed:
```
2016-10-06 11:37:52 - DEBUG UnitTestFramework: '#setup: 'Coordinated seq test''
2016-10-06 11:37:52 - DEBUG UnitTestFramework: '#setup ok: 'Coordinated seq test''
2016-10-06 11:37:52 - DEBUG UnitTestFramework: '#run: 'Coordinated seq test''
2016-10-06 11:37:56 - DEBUG UnitTestFramework: '#run ok: 'Coordinated seq test''
2016-10-06 11:37:56 - DEBUG UnitTestFramework: '#teardown: 'Coordinated seq test''
2016-10-06 11:37:56 - DEBUG UnitTestFramework: '#teardown ok: 'Coordinated seq test''
```

**Comment by larryonoff** [comment] 2016-10-06 13:58
PR with 'Coordinated seq test' enabled created, see thaliproject/Thali_CordovaPlugin/#1260.

**Closed** 2016-10-06 14:32 UTC
Labels: Android, bug, Node
