### ISSUE TITLE
Thali: Large amount of data exchanged compared to replicated one

### ISSUE THREAD

**Issue by lesn1kk** [thaliproject/Thali_CordovaPlugin#1964] opened 2017-09-27 12:37 UTC
The issue is that when we want to replicate for example with 64 kB of data (kiloBytes), when doc is added to PouchDB, a lot of additional data is exchanged compared to weight of doc itself. As @enricogior found out, the factor of exchanged data to doc weight is about x10 or even x11 on Android. This occurs in WiFi and Native modes, so it is not related to native part of Thali. 
This is concerning because when we replicate using Native radios, every additional byte is really slowing us down.
@yaronyg Are you familiar with this kind of behaviour? Is it just the way PouchDB finds out about changes or docs to exchange? Or it looks more like a bug?

**Comment by enricogior** [comment] 2017-09-27 12:47
When investigating issue https://github.com/thaliproject/Thali_CordovaPlugin/issues/1960 I added some extra logging to OpenSSL and to ThaliCore.
I noticed an extra amount of data exchanged between peers, I thought it was caused by the bug in ThaliCore that cause the replication to fail from time to time.
But it turned out it happens also when using WiFi on iOS and Android and the replication succeeds.

I log all the chunks of 16KB decrypted by OpenSSL and I compare them with the chunks sent by the peers using the MPCF: the amounts of bytes transferred match.
When I test in WiFi mode I only log the data process by OpenSSL and it matches the amount of data transferred when using the MPCF and the replication succeeds.
The factor is 11, so when replicating  a 64KB attachment, we exchange a total 704KB.

I also tested 512KB attachments, but currently the replication fails on both Android and iOS, but before failing, 4016KB are exchanged.

**Comment by yaronyg** [comment] 2017-09-27 15:52
Yikes. O.k. so I'm not sure what is going on here. Given that the data transfers are the same this would strongly imply a problem with PouchDB. But it should be fairly easy to log out all the requests/responses made by PouchDB and see if they are 10x what we would expect.

**Comment by enricogior** [comment] 2017-10-10 12:06
This turned out to be an application issue, @mlesnic provided a fix for it in ThaliTestApp.

**Closed as completed** 2017-10-20 12:47 UTC
Labels: bug
