### ISSUE TITLE
Switch from our custom version of PouchDB to the mainline version

### ISSUE THREAD

**Issue by andrew-aladev** [thaliproject/Thali_CordovaPlugin#870] opened 2016-08-15 15:18 UTC
I've checked many times that we are working properly with PouchDB in `vNext_aaladev_507` now. But we are catching an unhandled exception from PouchDB constantly. The problem is in `AbstractPouchDB.prototype.info`. It looks like `info` request was not aborted properly by PouchDB.

```
Trace: { [Error: connect ECONNREFUSED]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  status: 500 }
    at process.tests (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/lib/thaliTape.js:41:11)
    at process.emit (events.js:85:17)
    at process.emit (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/source-map-support/source-map-support.js:387:21)
    at Array.0 (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/lie/lib/index.js:128:19)
    at nextTick (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/immediate/lib/index.js:61:18)
    at process._tickCallback (node.js:917:13)
---------------------------------------------
    at scheduleDrain (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/immediate/lib/index.js:45:13)
    at immediate (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/immediate/lib/index.js:71:5)
    at unwrap (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/lie/lib/index.js:85:3)
    at QueueItem.otherCallRejected (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/lie/lib/index.js:81:3)
    at Object.handlers.reject (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/lie/lib/index.js:136:19)
    at onError (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/lie/lib/index.js:159:14)
    at /Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/lib/index.js:139:13
    at /Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/lib/index.js:110:11
    at /Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/argsarray/index.js:14:18
    at /Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/lib/index.js:2388:14
    at /Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/lib/index.js:5491:16
    at Request._callback (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/lib/index.js:5108:14)
    at self.callback (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/node_modules/request/request.js:200:22)
    at Request.emit (events.js:82:17)
    at Request.onRequestError (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/node_modules/request/request.js:831:8)
    at ClientRequest.emit (events.js:82:17)
    at CleartextStream.socketErrorListener (http.js:1173:9)
    at CleartextStream.emit (events.js:82:17)
    at Socket.onerror (tls.js:1457:17)
---------------------------------------------
    at Request.init (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/node_modules/request/request.js:202:10)
    at new Request (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/node_modules/request/request.js:142:8)
    at request (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/node_modules/request/index.js:55:10)
    at ajaxCore (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/lib/index.js:5105:10)
    at PouchAlt.ajax [as _ajax] (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/lib/index.js:5138:10)
    at ajax$$ (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/lib/index.js:5287:16)
    at /Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/lib/index.js:5485:7
    at Array.0 (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/lie/lib/index.js:88:21)
    at nextTick (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/immediate/lib/index.js:61:18)
    at process._tickCallback (node.js:917:13)
---------------------------------------------
    at scheduleDrain (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/immediate/lib/index.js:45:13)
    at immediate (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/immediate/lib/index.js:71:5)
    at unwrap (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/lie/lib/index.js:85:3)
    at QueueItem.otherCallFulfilled (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/lie/lib/index.js:75:3)
    at Object.handlers.resolve (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/lie/lib/index.js:115:21)
    at onSuccess (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/lie/lib/index.js:167:14)
    at Object.opts.complete (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/lib/index.js:1462:9)
    at fetched (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/lib/index.js:6050:14)
    at onSuccess (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/lib/index.js:5085:5)
    at Request._callback (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/lib/index.js:5127:7)
    at Request.self.callback (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/node_modules/request/request.js:200:22)
    at Request.emit (events.js:85:17)
    at Request.<anonymous> (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/node_modules/request/request.js:1067:10)
    at Request.emit (events.js:98:20)
    at IncomingMessage.<anonymous> (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/node_modules/request/request.js:988:12)
    at IncomingMessage.emit (events.js:98:20)
    at _stream_readable.js:889:16
    at process._tickCallback (node.js:917:13)
---------------------------------------------
    at Request.init (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/node_modules/request/request.js:203:10)
    at new Request (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/node_modules/request/request.js:142:8)
    at request (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/node_modules/request/index.js:55:10)
    at ajaxCore (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/lib/index.js:5105:10)
    at PouchAlt.ajax [as _ajax] (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/lib/index.js:5138:10)
    at ajax$$ (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/lib/index.js:5287:16)
    at /Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/lib/index.js:5992:15
    at Array.0 (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/lie/lib/index.js:88:21)
    at nextTick (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/immediate/lib/index.js:61:18)
    at process._tickCallback (node.js:917:13)
---------------------------------------------
    at scheduleDrain (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/immedi
ate/lib/index.js:45:13)
    at immediate (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/immediate/lib/index.js:71:5)
    at unwrap (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/lie/lib/index.js:85:3)
    at QueueItem.otherCallFulfilled (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/lie/lib/index.js:75:3)
    at Object.handlers.resolve (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/lie/lib/index.js:115:21)
    at onSuccess (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/lie/lib/index.js:167:14)
    at Object.opts.complete (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/lib/index.js:1462:9)
    at fetched (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/lib/index.js:6050:14)
    at onSuccess (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/lib/index.js:5085:5)
    at Request._callback (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/lib/index.js:5127:7)
    at Request.self.callback (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/node_modules/request/request.js:200:22)
    at Request.emit (events.js:85:17)
    at Request.<anonymous> (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/node_modules/request/request.js:1067:10)
    at Request.emit (events.js:98:20)
    at IncomingMessage.<anonymous> (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/node_modules/request/request.js:988:12)
    at IncomingMessage.emit (events.js:98:20)
    at _stream_readable.js:889:16
    at process._tickCallback (node.js:917:13)

Error: connect ECONNREFUSED
    at errnoException (net.js:837:11)
    at Object.afterConnect [as oncomplete] (net.js:829:19)
---------------------------------------------
    at CleartextStream.Readable.on (_stream_readable.js:657:33)
    at http.js:1383:12
    at process._tickCallback (node.js:917:13)
---------------------------------------------
    at ClientRequest.onSocket (http.js:1359:11)
    at ForeverAgentSSL.Agent.addRequest [as addRequestNoreuse] (http.js:895:9)
    at new ClientRequest (http.js:1044:16)
    at Object.exports.request (https.js:100:10)
    at Request.start (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/node_modules/request/request.js:753:32)
    at Request.onRequestError (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/node_modules/request/request.js:823:10)
    at ClientRequest.emit (events.js:82:17)
    at CleartextStream.socketCloseListener (http.js:1150:9)
    at CleartextStream.emit (events.js:98:20)
    at tls.js:644:10
    at process._tickCallback (node.js:917:13)
---------------------------------------------
    at Request.start (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/node_modules/request/request.js:799:12)
    at Request.end (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/node_modules/request/request.js:1418:10)
    at end (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/node_modules/request/request.js:580:14)
    at Object.<anonymous> (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/node_modules/request/request.js:594:7)
    at processImmediate [as _immediateCallback] (timers.js:370:15)
---------------------------------------------
    at Request.init (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/node_modules/request/request.js:538:3)
    at new Request (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/node_modules/request/request.js:142:8)
    at request (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/node_modules/request/index.js:55:10)
    at ajaxCore (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/lib/index.js:5105:10)
    at PouchAlt.ajax [as _ajax] (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/lib/index.js:5138:10)
    at ajax$$ (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/lib/index.js:5287:16)
    at /Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/lib/index.js:5485:7
    at Array.0 (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/lie/lib/index.js:88:21)
    at nextTick (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/immediate/lib/index.js:61:18)
    at process._tickCallback (node.js:917:13)
---------------------------------------------
    at scheduleDrain (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/immediate/lib/index.js:45:13)
    at immediate (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/immediate/lib/index.js:71:5)
    at unwrap (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/lie/lib/index.js:85:3)
    at QueueItem.otherCallFulfilled (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/lie/lib/index.js:75:3)
    at Object.handlers.resolve (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/lie/lib/index.js:115:21)
    at onSuccess (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/lie/lib/index.js:167:14)
    at Object.opts.complete (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/lib/index.js:1462:9)
    at fetched (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/lib/index.js:6050:14)
    at onSuccess (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/lib/index.js:5085:5)
    at Request._callback (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/lib/index.js:5127:7)
    at Request.self.callback (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/node_modules/request/request.js:200:22)
    at Request.emit (events.js:85:17)
    at Request.<anonymous> (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/node_modules/request/request.js:1067:10)
    at Request.emit (events.js:98:20)
    at IncomingMessage.<anonymous> (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/node_modules/request/request.js:988:12)
    at IncomingMessage.emit (events.js:98:20)
    at _stream_readable.js:889:16
    at process._tickCallback (node.js:917:13)
---------------------------------------------
    at Request.init (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/node_modules/request/request.js:203:10)
    at new Request (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/node_modules/request/request.js:142:8)
    at request (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/node_modules/request/index.js:55:10)
    at ajaxCore (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/lib/index.js:5105:10)
    at PouchAlt.ajax [as _ajax] (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/lib/index.js:5138:10)
    at ajax$$ (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/lib/index.js:5287:16)
    at /Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/lib/index.js:5992:15
    at Array.0 (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/lie/lib/index.js:88:21)
    at nextTick (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/immediate/lib/index.js:61:18)
    at process._tickCallback (node.js:917:13)
---------------------------------------------
    at scheduleDrain (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/immediate/lib/index.js:45:13)
    at immediate (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/immediate/lib/index.js:71:5)
    at unwrap (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/lie/lib/index.js:85:3)
    at QueueItem.otherCallFulfilled (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/lie/lib/index.js:75:3)
    at Object.handlers.resolve (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/lie/lib/index.js:115:21)
    at onSuccess (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/lie/lib/index.js:167:14)
    at Object.opts.complete (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/lib/index.js:1462:9)
    at fetched (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/lib/index.js:6050:14)
    at onSuccess (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb
/lib/index.js:5085:5)
    at Request._callback (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/lib/index.js:5127:7)
    at Request.self.callback (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/node_modules/request/request.js:200:22)
    at Request.emit (events.js:85:17)
    at Request.<anonymous> (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/node_modules/request/request.js:1067:10)
    at Request.emit (events.js:98:20)
    at IncomingMessage.<anonymous> (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/node_modules/request/request.js:988:12)
    at IncomingMessage.emit (events.js:98:20)
    at _stream_readable.js:889:16
    at process._tickCallback (node.js:917:13)
```

**Comment by andrew-aladev** [comment] 2016-08-15 15:43
Trace from the `AbstractPouchDB.prototype.info`

```
Trace
    at /Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/lib/index.js:2389:15
    at /Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/lib/index.js:5493:16
    at Request._callback (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/lib/index.js:5110:14)
    at self.callback (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/node_modules/request/request.js:200:22)
    at Request.emit (events.js:82:17)
    at Request.onRequestError (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/node_modules/request/request.js:831:8)
    at ClientRequest.emit (events.js:82:17)
    at CleartextStream.socketErrorListener (http.js:1173:9)
    at CleartextStream.emit (events.js:82:17)
    at Socket.onerror (tls.js:1457:17)
    at Socket.emit (events.js:98:20)
    at net.js:398:14
    at process._tickCallback (node.js:917:13)
---------------------------------------------
    at Request.init (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/node_modules/request/request.js:202:10)
    at new Request (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/node_modules/request/request.js:142:8)
    at request (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/node_modules/request/index.js:55:10)
    at ajaxCore (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/lib/index.js:5107:10)
    at PouchAlt.ajax [as _ajax] (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/lib/index.js:5140:10)
    at ajax$$ (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/lib/index.js:5289:16)
    at /Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/lib/index.js:5487:7
    at Array.0 (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/lie/lib/index.js:88:21)
    at nextTick (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/immediate/lib/index.js:61:18)
    at process._tickCallback (node.js:917:13)
---------------------------------------------
    at scheduleDrain (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/immediate/lib/index.js:45:13)
    at immediate (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/immediate/lib/index.js:71:5)
    at unwrap (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/lie/lib/index.js:85:3)
    at QueueItem.otherCallFulfilled (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/lie/lib/index.js:75:3)
    at Object.handlers.resolve (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/lie/lib/index.js:115:21)
    at onSuccess (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/lie/lib/index.js:167:14)
    at Object.opts.complete (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/lib/index.js:1462:9)
    at fetched (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/lib/index.js:6052:14)
    at onSuccess (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/lib/index.js:5087:5)
    at Request._callback (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/lib/index.js:5129:7)
    at Request.self.callback (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/node_modules/request/request.js:200:22)
    at Request.emit (events.js:85:17)
    at Request.<anonymous> (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/node_modules/request/request.js:1067:10)
    at Request.emit (events.js:98:20)
    at IncomingMessage.<anonymous> (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/node_modules/request/request.js:988:12)
    at IncomingMessage.emit (events.js:98:20)
    at _stream_readable.js:889:16
    at process._tickCallback (node.js:917:13)
---------------------------------------------
    at Request.init (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/node_modules/request/request.js:203:10)
    at new Request (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/node_modules/request/request.js:142:8)
    at request (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/node_modules/request/index.js:55:10)
    at ajaxCore (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/lib/index.js:5107:10)
    at PouchAlt.ajax [as _ajax] (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/lib/index.js:5140:10)
    at ajax$$ (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/lib/index.js:5289:16)
    at /Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/lib/index.js:5994:15
    at Array.0 (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/lie/lib/index.js:88:21)
    at nextTick (/Users/hiqouser/workspace/vNext_aaladev_507/Thali_CordovaPlugin/test/www/jxcore/node_modules/immediate/lib/index.js:61:18)
    at process._tickCallback (node.js:917:13)
```

**Comment by andrew-aladev** [comment] 2016-08-15 15:49
```
Request.prototype.onRequestError = function (error) {
  var self = this
  if (self._aborted) {
    return
  }
  if (self.req && self.req._reusedSocket && error.code === 'ECONNRESET'
      && self.agent.addRequestNoreuse) {
    self.agent = { addRequest: self.agent.addRequestNoreuse.bind(self.agent) }
    self.start()
    self.req.end()
    return
  }
  if (self.timeout && self.timeoutTimer) {
    clearTimeout(self.timeoutTimer)
    self.timeoutTimer = null
  }
  self.emit('error', error)
}
```

Request is emitting the error, so it is not in `aborted` state.

**Comment by andrew-aladev** [comment] 2016-08-15 16:45
We can fix this:

```
  if (opts.continuous && opts.since !== 'now') {
    this.db.info().then(function (info) {
      self.startSeq = info.update_seq;
    /* istanbul ignore next */
    }, function (err) {
      if (err.id === 'idbNull') {
        // db closed before this returned thats ok
        return;
      }
      throw err;
    })
    .catch(function () {});
  }
```

**Comment by andrew-aladev** [comment] 2016-08-15 17:12
We can make a workaround now:

```
  PouchAlt.prototype.info = function () {
    var self = this;
    return PouchAlt.super_.prototype.info.apply(this, arguments)
    .catch(function () {
      return { update_seq: 0 };
    });
  }
```

**Comment by yaronyg** [comment] 2016-08-15 21:16
I'm fairly sure that code has been completely replaced in new version of PouchDB. Check out https://github.com/pouchdb/pouchdb/blob/8d2af9bd78cea3a810ea67ef278d6ea6a5bd765a/packages/pouchdb-core/src/changes.js#L139

A better use of our time would probably be to run the build tests for our custom version of Express-PouchDB with the latest PouchDB and debug the failures there and that way we can just switch to using the latest PouchDB and get rid of our custom build all together.

1. git clone https://github.com/yaronyg/pouchdb-server
2. git checkout thali-release
2. npm install
3. npm run build
4. npm run test-pouchdb-minimum

The problem is that when I run step 3 it fails on my machine and no I have absolutely no idea why. I just can't spend more time figuring it out but this is a regression and probably has something to do with something bad on my machine. I did nuke the repo and re-clone but it didn't fix it.

But the dirty secret is that pouchd isn't really a true mono-repo so you can replace step 3 with:
* cd packages/express-pouchdb
* npm install
* cd ../..
Then continue with 'npm run test-pouchdb-minimum'

This runs using a specific release of PouchDB that is set in test-setup.sh, look for the variable POUCHDB_SHA which contains the git sha of the release off master to use.

I reset it to 836987a (the latest commit on Master) and all tests are passing. So I tried to roll it back a bit to e318490 which is the last official release of PouchDB and it worked just fine. So why don't you change our dependency on our magic version of PouchDB to the last released version and stop us from even building our magic version and see if the problem still exists? If not then check in those changes!

**Comment by yaronyg** [comment] 2016-08-16 17:21
Note that we should jump on this as soon as we have Android back up and running. It will simplify deployment and shorten build times. Not to mention that it will get rid of a nasty bug.

**Comment by andrew-aladev** [comment] 2016-08-24 13:33
I've received [issue](https://github.com/rlidwka/sinopia/issues/278). Workaround works.

**Comment by yaronyg** [comment] 2016-08-25 16:26
I put this into vNext_yarong_417_812 which has a PR #928 so we can close this.

**Closed by yaronyg** 2016-08-25 16:26 UTC
Labels: 2 - Ready, estimate - 2, P1
