### ISSUE TITLE
ThaliCore: Active relays are not properly cleaned up

### ISSUE THREAD

**Issue by mlesnic** [thaliproject/Thali_CordovaPlugin#1912] opened 2017-06-20 14:16 UTC
At some point, when we want to send a Notification to other peer about changes, the multiConnect resolves immediately, because there is active connection with this particular peer. But, in fact, this connection is probably corrupted, because it causes us either to fail with `Could not establish TCP connection` error or just our httpRequest hangs.

[Here](https://gist.github.com/mlesnic/1e089e3ac4e7a21ea1a6b201f807159c#file-logs-L333) you can see attempt to `multiConnect` with other peer, but we failed with `Could not establish TCP connection`. [Here](https://gist.github.com/mlesnic/1e089e3ac4e7a21ea1a6b201f807159c#file-logs-L458) you can see another attempt to connect with same peer, but we fail silently or just hang, which causes `NotificationAction` to not resolve at all.

After changes in peerPool to call `thaliMobileNativeWrapper.disconnect` on peer with which we failed with `Could not establish TCP connection` when trying to get beacon, it works smoothly to the moment, when [httpRequest](https://github.com/thaliproject/Thali_CordovaPlugin/blob/master/thali/NextGeneration/notification/thaliNotificationAction.js#L163) just hangs.

**Comment by enricogior** [comment] 2017-06-21 11:13
Definitely a bug in `TCPListener` that never invokes `didStoppedListeningHandler()` (it should be called when the connection to the peer is closed), therefore the `BrowserRelay` is not closed and the `BrowserManager` will keep it in the `activeRelays` list and it will try to reuse it next time the client tries to reconnect to the same peer.

**Comment by mlesnic** [comment] 2017-06-21 13:00
Also, this causes to keep alive a lot of virtual sockets and eventually it reaches limit and we are facing again the issue when we call create virtual socket and nothing happens after that.

**Comment by enricogior** [comment] 2017-06-22 13:20
@mlesnic yes you are right, when active relays are left behind they cause the virtual sockets leak.

The code has several issues:
 - the `lostPeerHandler` is not removing the relay for that peer from the activeRelays list, so we are trying to reuse an existing activeRelay even when we shouldn't
 - the current implementation of `BrowserManager.connectToPeer()` assumes that an activeRelay is actually working so it calls the completion method right away, that in turn will cause the node layer to assume it can proceed sending data to the remote peer. Because of that the connection will eventually fail for timeout error.
 - because the [specification requires](https://github.com/thaliproject/Thali_CordovaPlugin/blob/53ae008b37e26c49ca3f5e08d3159d52546b019c/thali/NextGeneration/thaliMobileNative.js#L87) `BrowserManager.connectToPeer()` to be idempotent is not so trivial to fix the current behavior.

The current workaround for the node code is to always call `disconnect()` before calling `connectToPeer()` in order to be sure to avoid the active relays bugs.

**Comment by mlesnic** [comment] 2017-06-23 11:22
After latest fix, we disconnect with peers that are also available. The scenario is that we lost connection to peer with generation 2 when we are trying to replicate with peer with generation 4. But, after we lost peer with generation 2, we disconnect with peer with generation 4, which causes us to stop working.

Sample logs:
```ThaliCore] TCPListener.socket(_:didAcceptNewSocket:)
[ThaliCore] BrowserRelay.createVirtualSocket(with:)
[ThaliCore] Session.startOutputStream(with:) peer:232894B7-AADA-4F5C-8B64-117370310B91:4
[ThaliCore] Session.session(_:didReceive:withName:fromPeer:) peer:232894B7-AADA-4F5C-8B64-117370310B91:4
2017-06-23 13:16:43.005811+0200 ThaliTestApp[361:43168] [ViceroyTrace] [ICE][ERROR]     Send BINDING_REQUEST failed(C01A0041).
2017-06-23 13:16:43.040717+0200 ThaliTestApp[361:43168] [ViceroyTrace] [ICE][ERROR]     Send BINDING_REQUEST failed(C01A0041).
2017-06-23 13:16:43.083501+0200 ThaliTestApp[361:43168] [ViceroyTrace] [ICE][ERROR]     Send BINDING_REQUEST failed(C01A0041).
2017-06-23 11:16:43 - DEBUG thaliReplicationPeerAction: 'Replication resumed'
[ThaliCore] TCPListener.socket(_:didAcceptNewSocket:)
[ThaliCore] BrowserRelay.createVirtualSocket(with:)
[ThaliCore] Session.startOutputStream(with:) peer:232894B7-AADA-4F5C-8B64-117370310B91:4
[ThaliCore] Session.session(_:didReceive:withName:fromPeer:) peer:232894B7-AADA-4F5C-8B64-117370310B91:4
2017-06-23 13:16:43.149939+0200 ThaliTestApp[361:43168] [ViceroyTrace] [ICE][ERROR]     Send BINDING_REQUEST failed(C01A0041).
[ThaliCore] TCPListener.socket(_:didAcceptNewSocket:)
[ThaliCore] BrowserRelay.createVirtualSocket(with:)
[ThaliCore] Session.startOutputStream(with:) peer:232894B7-AADA-4F5C-8B64-117370310B91:4
[ThaliCore] Session.session(_:didReceive:withName:fromPeer:) peer:232894B7-AADA-4F5C-8B64-117370310B91:4
[ThaliCore] Browser.browser(_:lostPeer:) lost peer:232894B7-AADA-4F5C-8B64-117370310B91:2
[ThaliCore] BrowserManager.lostPeerHandler peer:Peer(uuid: "232894B7-AADA-4F5C-8B64-117370310B91", generation: 2)
[ThaliCore] Session.disconnect() peer:232894B7-AADA-4F5C-8B64-117370310B91:4
[ThaliCore] Session.session(_:peer:didChange:) peer:232894B7-AADA-4F5C-8B64-117370310B91:4 state:connected -> notConnected
[ThaliCore] Session.sessionNotConnected peer:232894B7-AADA-4F5C-8B64-117370310B91
[ThaliCore] BrowserRelay.closeRelay() disconnecting:false
[ThaliCore] TCPListener.stopListeningForConnectionsAndDisconnectClients() port:56579
[ThaliCore] VirtualSocket.closeStreams()
[ThaliCore] TCPListener.socketDidDisconnect(_:withError:) listening socket error:nil
[ThaliCore] BrowserRelay.didCloseVirtualSocketStreamsHandler
[ThaliCore] VirtualSocket.closeStreams()
[ThaliCore] VirtualSocket exited RunLoop
[ThaliCore] BrowserRelay.didCloseVirtualSocketStreamsHandler
[ThaliCore] VirtualSocket.closeStreams()
[ThaliCore] VirtualSocket exited RunLoop
[ThaliCore] BrowserRelay.didCloseVirtualSocketStreamsHandler
[ThaliCore] VirtualSocket.closeStreams()
[ThaliCore] VirtualSocket exited RunLoop
[ThaliCore] BrowserRelay.didCloseVirtualSocketStreamsHandler
[ThaliCore] VirtualSocket.deinit
[ThaliCore] VirtualSocket.deinit
[ThaliCore] VirtualSocket.deinit
[ThaliCore] Session.disconnect() peer:232894B7-AADA-4F5C-8B64-117370310B91:4
[ThaliCore] Session.sessionNotConnected removed peer:232894B7-AADA-4F5C-8B64-117370310B91
[ThaliCore] VirtualSocket exited RunLoop
[ThaliCore] VirtualSocket.deinit```

We start output stream with peer with generation 4 and in meantime we lost peer with generation 2, but we call disconnect on peer with generation 4

**Comment by enricogior** [comment] 2017-06-23 11:28
@mlesnic can you describe the sequence of actions on ThaliTestApp to reproduce the problem?

**Comment by mlesnic** [comment] 2017-06-23 11:34
Just start Thali on both devices, on first using Init Thali #1, on second Init Thali #2. Then, start adding data on one of the devices. Start adding data one by another and wait when it replicate. If you will do it relatively slowly, you should see data passing almost always. Then start adding data more quickly, so on one device add like 5-6 docs in a row. Some of them should replicate, but not all of them. At some point you will se similar logs as I posted above.
Note: You should use the peerPool workaround. I will push it in new branch and ping you.

**Comment by enricogior** [comment] 2017-06-23 20:31
@mlesnic I've been having problems running ThaliTestApp.
I used the `master_mlesnic_iOS_workaround` branch for Thali_CordovaPlugin and the `master_update_build_for_xcode8` branch for ThaliTestApp.
I followed the instructions in the ThaliTestApp readme to build the app.
When the app starts on device 1, I tap `Native` then `Init Thali #1` then `Start Thali`.
On device 2, I tap `Native` then `Init Thali #2` then `Start Thali`.
I see in the Xcode console log that everything is working as expected.
Then I tap `Add data` on device 1, I see the data been replicated on device 2 but then I get this error on both devices, after that the `Add data` button doesn't work anymore and it doesn't add any data.

```
2017-06-23 20:20:32 - DEBUG thaliMobileNativeWrapper: 'Received peerAvailabilityChanged event from native layer [{"peerAvailable":true,"peerIdentifier":"2292326F-3367-426C-BEB4-A1B5B2ECBDA3","generation":2}]'
2017-06-23 20:20:32 - DEBUG thaliMobileNativeWrapper: 'Received peer availability changed event with {"peerAvailable":true,"peerIdentifier":"2292326F-3367-426C-BEB4-A1B5B2ECBDA3","generation":2}'
2017-06-23 20:20:32 - DEBUG thaliMobileNativeWrapper: 'handlePeerAvailabilityChanged - Emitting {"peerIdentifier":"2292326F-3367-426C-BEB4-A1B5B2ECBDA3","peerAvailable":true,"generation":2,"portNumber":null}'
2017-06-23 20:20:32 - DEBUG thaliMobile: 'Emitting peerAvailabilityChanged from handlePeer {"peerIdentifier":"2292326F-3367-426C-BEB4-A1B5B2ECBDA3","connectionType":"MPCF","peerAvailable":true,"generation":2,"newAddressPort":false}'
2017-06-23 20:20:32 - DEBUG thaliManager: 'connected pskIdentity FzDwLQcPeeF3N6igxXbo8Qyof69tZIGmNvIjL6gX6og for path /db/testdb/_bulk_docs'
2017-06-23 20:20:32 - DEBUG thaliReplicationPeerAction: 'Got paused with -  '
2017-06-23 20:20:32 - DEBUG thaliManager: 'connected pskIdentity FzDwLQcPeeF3N6igxXbo8Qyof69tZIGmNvIjL6gX6og for path /db/testdb/_local/tz0uF8qawL8QA67sP.qHSA%3D%3D'
2017-06-23 20:20:32 - DEBUG thaliManager: 'connected pskIdentity FzDwLQcPeeF3N6igxXbo8Qyof69tZIGmNvIjL6gX6og for path /db/testdb/_bulk_docs'

2017-06-23 20:20:41 - DEBUG thaliReplicationPeerAction: 'We called _complete with error: No activity time out  and it caused us to complete'
2017-06-23 20:20:41 - DEBUG thaliReplicationPeerAction: 'We called _complete with  but this is a second call and so we ignored it'
2017-06-23 20:20:41 - DEBUG thaliPeerPoolOneAtATime: 'action returned with error from startError: No activity time out - Action ID: 2, Action Type: ReplicationAction, Connection Type: MPCF, Peer Identifier: BNTJE6l6zcgm9yLjRyXn8Z1f2jA5m_60gYIDaJxiLDYJMUmV_5LJMHBSA9RVmjp9tyWQWkn0BWk6cvQiWpt86IE'
uncaught promise rejection, error: 'TypeError: thaliMobileNativeWrapper._getServersManager(...) is null', stack: 'ThaliPeerPoolOneAtATime.prototype._bluetoothEnqueue/</</<@/private/var/containers/Bundle/Application/242D35C3-2365-4387-BE11-119E24A9AA5B/ThaliTestApp.app/www/jxcore/node_modules/thali/NextGeneration/thaliPeerPool/thaliPeerPoolOneAtATime.js:254:15
unwrap/<@/private/var/containers/Bundle/Application/242D35C3-2365-4387-BE11-119E24A9AA5B/ThaliTestApp.app/www/jxcore/node_modules/lie/lib/index.js:88:21
nextTick@/private/var/containers/Bundle/Application/242D35C3-2365-4387-BE11-119E24A9AA5B/ThaliTestApp.app/www/jxcore/node_modules/immediate/lib/index.js:61:7
$0a@node.js:924:1
'
process exited, code: '2', signal: 'undefined'

```

**Comment by mlesnic** [comment] 2017-06-26 09:14
@enricogior You are using ThaliPeerPoolOneAtATime, you should use ThaliPeerPoolDefault. Check `app.js`, you have to comment/uncomment it in two places.

**Comment by enricogior** [comment] 2017-06-26 13:29
The root bug here is a ThaliCore internal design bug:
 - the AdvertiserManger [creates a new session](https://github.com/thaliproject/thali-ios/blob/93f254222ce2585d1d17f6296001f51300584e70/ThaliCore/MultipeerConnectivity/AdvertiserManager.swift#L101) for each new generation.
 - the BrowserManager doesn't create new sessions for new generations, instead it [tries to reuse](https://github.com/thaliproject/thali-ios/blob/93f254222ce2585d1d17f6296001f51300584e70/ThaliCore/MultipeerConnectivity/BrowserManager.swift#L147) the session used by the previous generation.

Given that the documentation says the caller can call `connect` to the same peer multiple times without having to call `disconnect` in between, the current implementation cannot work.
There are two possible ways to fix this:
 A) change the API specification so that a caller cannot call connect to the same peer twice without calling disconnect in between.
 B) change the BrowserManager implementation and store browserRelays with peerID + generation and never try to use a browserRelay created for a previous generation.

I guess we should go with option B. @yaronyg  can you please confirm? Thank you.

**Comment by yaronyg** [comment] 2017-06-27 21:37
Yes, I like B. But we only need to connect whatever the latest generation is.

**Comment by enricogior** [comment] 2017-06-28 05:50
@yaronyg Yes, the fix always connects to the last generation.

**Comment by enricogior** [comment] 2017-07-06 18:24
Fixed in https://github.com/thaliproject/thali-ios/commits/master-enrico-error-handling-tmp

**Closed** 2017-07-24 09:59 UTC
Labels: bug, iOS, ready
