### ISSUE TITLE
App crashes on iOS

### ISSUE THREAD

**Issue by czyzm** [thaliproject/Thali_CordovaPlugin#1485] opened 2016-11-04 08:38 UTC
I have made some tests using Stanton between 4 devices (2x S7 and 2x iPhones SE) using WiFi mode. All was working. Then I left the devices for some time (about 9 minutes). Note that app on iPhones was launched from xCode so it was kept foreground all that time. Then I added some data on one of iPhones. The app stopped in xCode in JXCore.m at line:

`result = JX_LoopOnce();`

with `EXC_BAD_ACCESS`.

Here are the logs from two iPhones:
[Thali55](https://gist.github.com/czyzm/9cb9148d998a66311fc8b56c8cf0f770) - the one on which we have the failure
[Thali56](https://gist.github.com/czyzm/5ad8826f9f541c9b8903cc99da25006f)

The change that caused the crash can be see in logs at 2016-11-04 08:19:17. Note that on Thali56 I tried later also sending some data and it worked.

**Comment by enricogior** [comment] 2016-11-04 08:55
@czyzm did you get a call stack in Xcode?

**Comment by czyzm** [comment] 2016-11-04 09:04
Here is the snapshot from xCode. This is the same issue occuring on the other iPhone (Thali56).
<img width="1440" alt="screen shot 2016-11-04 at 09 59 14" src="https://cloud.githubusercontent.com/assets/16643097/20000062/ebc44028-a275-11e6-8b13-a190e33b1f5f.png">

**Comment by larryonoff** [comment] 2016-11-04 09:37
@czyzm are you able reproducing the same issue when debugging disabled without launching from Xcode ?

**Comment by czyzm** [comment] 2016-11-04 10:15
Yesterday during my tests without xCode it happened that the app was crashing suddenly. It looked exactly as this issue - crash was happening when some Thali replication was starting. After starting app again all worked fine.

**Comment by czyzm** [comment] 2016-11-04 13:41
Just for additional information. I was able to reproduce it with Stanton app. Didn't happen for me with ThaliTestApp 10 minutes test. With Stanton it happened without app going background. Just adding some data and starting/stopping Thali. However, no clear scenario.

**Comment by larryonoff** [comment] 2016-11-04 13:53
We're trying to reproduce it on our devices with ThaliTestApp, but if we're unable to reproduce it would be problematic to fix the issue.

**Comment by yaronyg** [comment] 2016-11-05 00:23
@enricogior I need you to take point on this. I would suggest that the first step is getting thaliproject/Thali_CordovaPlugin#1413 checked in and fixed. We know that the way we are handling some SM exceptions causes crashes. So maybe that is what is happening here. Once you have confirmed that Rockwell is seeing the crash with 1413 fixed then the next step is to instruct Rockwell on what they have to do so we can get a stack. Without that we can't even investigate this problem!

**Comment by czyzm** [comment] 2016-11-07 09:32
I was able to reproduce it with the new version of ThaliTestApp. After the initialization of Thali on two devices just press "Start test" button. It will start adding data, stopping and starting Thali. I tried it 3 times and I got the crash after couple of minutes (twice after about 8 minutes, once after 4 minutes).

Remember to turn off auto-lock in iOS because the app is not prepared for going background. The current version uses express-pouchdb@1.0.6-thali.

**Comment by yaronyg** [comment] 2016-11-07 19:06
@czyzm Which branch did you use of ThaliTestApp? Please clarify so we can make a proper repo. Best is if you give us a URL to the specific commit. Then we can assign to @enricogior to investigate.

**Comment by enricogior** [comment] 2016-11-07 21:25
I can repro the problem, it's not caused by the improper signal handler https://github.com/thaliproject/Thali_CordovaPlugin/issues/1413
It looks like a legit access violation in libuv. I'm trying to get Xcode to load the proper symbols and source files for the libjx.a library in order to better investigate the bug.

**Comment by czyzm** [comment] 2016-11-08 06:30
For clarity, I used following commits:
ThaliTestApp (thaliproject): b86048b82a9696db50826315afdd7b94d271b6ac
Thali_CordovaPlugin: bb7816da80fb263db66ee49d2d77391ce6413064

**Comment by enricogior** [comment] 2016-11-29 08:14
Got a clean callstack for the crash, it looks identical of the crash we have on desktop https://github.com/thaliproject/Thali_CordovaPlugin/issues/1091

```
* thread #15: tid = 0x6d2b2, 0x00000001001da1f8 ThaliTestApp`___lldb_unnamed_symbol377$$ThaliTestApp + 48, stop reason = EXC_BAD_ACCESS (code=1, address=0x100000002)
    frame #0: 0x00000001001da1f8 ThaliTestApp`___lldb_unnamed_symbol377$$ThaliTestApp + 48
    frame #1: 0x00000001001dbeec ThaliTestApp`js::gc::MarkValueRoot(JSTracer*, JS::Value*, char const*) + 92
    frame #2: 0x00000001001df848 ThaliTestApp`js::gc::GCRuntime::markRuntime(JSTracer*, js::gc::GCRuntime::TraceOrMarkRuntime, js::gc::GCRuntime::TraceRootsOrUsedSaved) + 460
    frame #3: 0x00000001002732f0 ThaliTestApp`js::gc::GCRuntime::beginMarkPhase(JS::gcreason::Reason) + 1228
    frame #4: 0x00000001002759d8 ThaliTestApp`js::gc::GCRuntime::incrementalCollectSlice(long long, JS::gcreason::Reason) + 384
    frame #5: 0x0000000100275ed0 ThaliTestApp`js::gc::GCRuntime::gcCycle(bool, long long, js::JSGCInvocationKind, JS::gcreason::Reason) + 236
    frame #6: 0x00000001002761e4 ThaliTestApp`js::gc::GCRuntime::collect(bool, long long, js::JSGCInvocationKind, JS::gcreason::Reason) + 240
    frame #7: 0x000000010029d934 ThaliTestApp`JSObject::create(js::ExclusiveContext*, js::gc::AllocKind, js::gc::InitialHeap, JS::Handle<js::Shape*>, JS::Handle<js::types::TypeObject*>) + 168
    frame #8: 0x0000000100290e38 ThaliTestApp`___lldb_unnamed_symbol726$$ThaliTestApp + 328
    frame #9: 0x0000000100290b60 ThaliTestApp`js::NewObjectWithGivenProto(js::ExclusiveContext*, js::Class const*, js::TaggedProto, JSObject*, js::gc::AllocKind, js::NewObjectKind) + 396
    frame #10: 0x00000001002e8c5c ThaliTestApp`js::ErrorObject::create(JSContext*, JSExnType, JS::Handle<JSString*>, JS::Handle<JSString*>, unsigned int, unsigned int, js::ScopedJSFreePtr<JSErrorReport>*, JS::Handle<JSString*>) + 204
    frame #11: 0x0000000100267288 ThaliTestApp`Error(JSContext*, unsigned int, JS::Value*) + 420
    frame #12: 0x00000001002f5aac ThaliTestApp`js::Invoke(JSContext*, JS::CallArgs, js::MaybeConstruct) + 328
    frame #13: 0x000000010026c178 ThaliTestApp`js_fun_apply(JSContext*, unsigned int, JS::Value*) + 812
    frame #14: 0x00000001002f5aac ThaliTestApp`js::Invoke(JSContext*, JS::CallArgs, js::MaybeConstruct) + 328
    frame #15: 0x00000001002f2844 ThaliTestApp`___lldb_unnamed_symbol930$$ThaliTestApp + 23616
    frame #16: 0x00000001002ecbd0 ThaliTestApp`js::RunScript(JSContext*, js::RunState&) + 244
    frame #17: 0x00000001002f5bc4 ThaliTestApp`js::Invoke(JSContext*, JS::CallArgs, js::MaybeConstruct) + 608
    frame #18: 0x000000010026bd5c ThaliTestApp`js_fun_call(JSContext*, unsigned int, JS::Value*) + 180
    frame #19: 0x00000001002f5aac ThaliTestApp`js::Invoke(JSContext*, JS::CallArgs, js::MaybeConstruct) + 328
    frame #20: 0x00000001002f2844 ThaliTestApp`___lldb_unnamed_symbol930$$ThaliTestApp + 23616
    frame #21: 0x00000001002ecbd0 ThaliTestApp`js::RunScript(JSContext*, js::RunState&) + 244
    frame #22: 0x00000001002f5bc4 ThaliTestApp`js::Invoke(JSContext*, JS::CallArgs, js::MaybeConstruct) + 608
    frame #23: 0x00000001002f5ea4 ThaliTestApp`js::Invoke(JSContext*, JS::Value const&, JS::Value const&, unsigned int, JS::Value const*, JS::MutableHandle<JS::Value>) + 376
    frame #24: 0x000000010024e3bc ThaliTestApp`JS_CallFunctionValue(JSContext*, JS::Handle<JSObject*>, JS::Handle<JS::Value>, JS::HandleValueArray const&, JS::MutableHandle<JS::Value>) + 76
    frame #25: 0x0000000100169b34 ThaliTestApp`MozJS::Value::Call(MozJS::Value const&, int, MozJS::Value*) const + 300
    frame #26: 0x0000000100147b24 ThaliTestApp`node::MakeCallback(node::commons*, MozJS::Value const&, MozJS::Value const&, int, MozJS::Value*) + 248
    frame #27: 0x0000000100484420 ThaliTestApp`NanCallback::Call_(MozJS::Value, int, MozJS::Value*) + 120
    frame #28: 0x0000000100484110 ThaliTestApp`NanAsyncWorker::HandleErrorCallback() + 192
    frame #29: 0x0000000100483fac ThaliTestApp`NanAsyncWorker::WorkComplete() + 48
    frame #30: 0x000000010047f0c8 ThaliTestApp`leveldown::IOWorker::WorkComplete() + 56
    frame #31: 0x00000001004834c4 ThaliTestApp`NanAsyncExecuteComplete(uv_work_s*) + 32
    frame #32: 0x00000001004596c8 ThaliTestApp`uv__work_done + 180
    frame #33: 0x0000000100450700 ThaliTestApp`___lldb_unnamed_symbol3035$$ThaliTestApp + 88
    frame #34: 0x00000001004508c8 ThaliTestApp`___lldb_unnamed_symbol3036$$ThaliTestApp + 168
    frame #35: 0x000000010045c8d4 ThaliTestApp`uv__io_poll_jx + 1260
    frame #36: 0x0000000100450f9c ThaliTestApp`uv_run_jx + 332
  * frame #37: 0x00000001000a0130 ThaliTestApp`+[JXcore threadMain](self=JXcore, _cmd="threadMain") + 380 at JXcore.m:410
    frame #38: 0x000000018807747c Foundation`__NSThread__start__ + 1024
    frame #39: 0x0000000186624850 libsystem_pthread.dylib`_pthread_body + 240
    frame #40: 0x0000000186624760 libsystem_pthread.dylib`_pthread_start + 284
    frame #41: 0x0000000186621dac libsystem_pthread.dylib`thread_start + 4
```

**Comment by enricogior** [comment] 2016-12-16 14:34
This has been fixed by https://github.com/thaliproject/jxcore/commit/297022cf8f5d230e299eed105fead050b314a4a9

**Closed** 2016-12-16 14:34 UTC
Labels: bug, jxcore
