### ISSUE TITLE
Android doesn't notify our BtLib about scan result from ble scanner

### ISSUE THREAD

**Issue by evabishchevich** [thaliproject/Thali_CordovaPlugin#1005] opened 2016-09-08 15:11 UTC

**Comment by evabishchevich** [comment] 2016-09-13 14:10
Probably the root of evil is the same like in thaliproject/Thali_CordovaPlugin_BtLibrary#88 .

**Comment by evabishchevich** [comment] 2016-09-14 14:40
Found out thaliproject/Thali_CordovaPlugin#1037 while working on this issue

**Comment by yaronyg** [comment] 2016-09-14 14:53
Blocked on an issue with test server that we should be able to resolve very soon.

**Comment by yaronyg** [comment] 2016-10-15 00:55
Please confirm if this issue still exists, otherwise please close it.

**Comment by yaronyg** [comment] 2016-11-17 00:30
@evabishchevich Does this issue still exist?

**Comment by vasilevskayaem** [comment] 2016-11-18 16:55
can't reproduce

**Comment by evabishchevich** [comment] 2016-11-21 10:38
@yaronyg @vasilevskayaem See the https://github.com/thaliproject/Thali_CordovaPlugin_BtLibrary/issues/88#issuecomment-261901895

**Closed** 2016-11-21 10:38 UTC
Labels: Android, bug
