### ISSUE TITLE
Some tests are failing because of zombie advertisers.

### ISSUE THREAD

**Issue by dersim-davaod** [thaliproject/Thali_CordovaPlugin#1856] opened 2017-04-18 13:44 UTC
Previously we face with similar issue (see ticket #1323)

Earlier I've seen incorrect behaviour in `origin/master_dersim_temp_latest_fixes` branch.
But now on the same branch it's hard to reproduce it.

Tests that are failing when running among other from `testTahliMobileNative.js`, but fine when running separately:
`Can connect to remote peer`
`Client to server request coordinated`
`Can shift large amounts of data`

**Comment by enricogior** [comment] 2017-05-18 09:18
I've also run into random failures due to TimeoutError with:
`Can shift data`
`Can shift data via parallel connections`

**Comment by enricogior** [comment] 2017-05-19 10:33
I've added logs to ThaliCore and I've found the cause of the failure.
The zombie advertisers are not causing the bug, they are exposing the bug.
When a peer is discovered, the test connects to the MPCF localhost virtual socket right away without waiting for the underling MPCF connection to be established.
In case of zombie advertisers, the MPCF connection will fail when the device sends the `invite to connect` request. That failure is not reported to the node layer and the test will wait on the established connection to the virtual socket until the timeout will expire.

This is the log of test `Can shift data via parallel connections` executed after test `Can shift data`
The peer `54214CC8-3B5B-4105-983D-16791668BD5C` if a zombie peer from the previous test.
```
ok 7 Can call startListeningForAdvertisements without error
MPCF Browser FOUND PEER 54214CC8-3B5B-4105-983D-16791668BD5C:0
connecting to peer: { peerAvailable: true,
peerIdentifier: '54214CC8-3B5B-4105-983D-16791668BD5C',
generation: 0 }
2017-05-19 08:49:23 - DEBUG thaliMobileNativeTestUtils: 'Issuing multiConnect for 54214CC8-3B5B-4105-983D-16791668BD5C (syncValue: 3Yctt68ssCsbcH6iKNikVQqnbQHz4wSS)'
2017-05-19 08:49:23 - DEBUG thaliMobileNativeTestUtils: 'Got 'multiConnect' callback'
MPCF BrowserManager connectToPeer
2017-05-19 08:49:23 - DEBUG thaliMobileNativeWrapper: 'multiConnectResolved: {"syncValue":"3Yctt68ssCsbcH6iKNikVQqnbQHz4wSS","error":null,"portNumber":51924}'
2017-05-19 08:49:23 - DEBUG thaliMobileNativeTestUtils: 'Got multiConnectResolved -syncValue: '3Yctt68ssCsbcH6iKNikVQqnbQHz4wSS', error: 'null', listeningPort: '51924''
Connecting to the localhost:51924
Connecting to the localhost:51924
Connecting to the localhost:51924
Connected to the localhost:51924
Connected to the localhost:51924
Connected to the localhost:51924
2017-05-19 10:49:23.407461+0200 ThaliTest[585:191408] [ViceroyTrace] [ICE][ERROR] Send BINDING_REQUEST failed(C01A0041).
ok 8 correct string length
2017-05-19 08:49:23 - DEBUG testThaliMobileNative: 'Client sends data (16384 bytes):'
ok 9 correct string length
2017-05-19 08:49:23 - DEBUG testThaliMobileNative: 'Client sends data (16384 bytes):'
ok 10 correct string length
2017-05-19 08:49:23 - DEBUG testThaliMobileNative: 'Client sends data (16384 bytes):'
2017-05-19 08:49:23 - DEBUG testThaliMobileNative: 'Client data flushed'
2017-05-19 08:49:23 - DEBUG testThaliMobileNative: 'Client data flushed'
2017-05-19 08:49:23 - DEBUG testThaliMobileNative: 'Client data flushed'
MPCF Browser LOST PEER 54214CC8-3B5B-4105-983D-16791668BD5C:0
```
What is missing in that log is the `MPCF BrowserManager inviteToConnect OK` entry instead of `MPCF Browser LOST PEER 54214CC8-3B5B-4105-983D-16791668BD5C:0`
As you can see the `LOST PEER` error occurs after the `Connected to the localhost:51924` has already been executed.
Running the test by itself, alleviates the problem, but doesn't fix it, sometimes (rarely but it happens) the test fails because of internal MPCF problems connecting to the other device.
This is one of those cases, the test `Can shift data` was the only test executed and it failed for the same reason, because it doesn't handle the MPCF connection error properly:
```
2017-05-19 10:06:35.429415+0200 ThaliTest[904:289655] [MCNearbyServiceAdvertiser] Failed to send dictionary [{
MCNearbyServiceInviteIDKey = 0;
MCNearbyServiceMessageIDKey = 1;
MCNearbyServiceRecipientPeerIDKey = <de30926a 0cac5b29 26313033 41383534 422d3931 43362d34 3937322d 41303646 2d393136 44424645 35354330 323a30>;
MCNearbyServiceSenderPeerIDKey = <9e65417b ace1dd10 24423435 44464638 432d3139 46392d34 3534442d 38363033 2d453032 41333031 39353632 34>;
}] to peer [B45DFF8C-19F9-454D-8603-E02A30195624,2CE1DD10].
2017-05-19 10:06:35.429530+0200 ThaliTest[904:290116] [MCNearbyServiceAdvertiser] Data from peer [B45DFF8C-19F9-454D-8603-E02A30195624,2CE1DD10] received with error Connection closed.
```

**Comment by mlesnic** [comment] 2017-07-27 04:35
Fix was merged to master.

**Closed by mlesnic** 2017-07-27 04:35 UTC
Labels: iOS, Node
