### ISSUE TITLE
EventEmitter memory leak

### ISSUE THREAD

**Issue by andrew-aladev** [thaliproject/Thali_CordovaPlugin#877] opened 2016-08-15 22:13 UTC
This bug is very hard to be reproduced. Please run `bv_tests/testThaliManagerCoordinated.js` many times. For example:

```
for i in {1..100}; do jx runCoordinatedTests.js --filter=bv_tests/testThaliManagerCoordinated.js; done > log.txt
grep -i "leak" log.txt
```

I have 3 duplicates:
```
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
```

We can fix this issue in future in order to start using EventEmitter.

**Comment by yaronyg** [comment] 2016-08-16 17:24
This shouldn't be marked as a jxcore bug. The jxcore tag is just for bugs in the jxcore software itself. If this is a bug it's in our software, not JXcore's.

I'm also not sure if this is a bug. I would need to see testThaliManagerCoordinated but if it is creating a large number of listeners in a short period of time then it's possible that the the code removing listeners can get behind the code creating listeners and that will then trigger this warning.

**Comment by yaronyg** [comment] 2016-10-06 16:43
This is now a dupe of thaliproject/Thali_CordovaPlugin#1259

**Closed by yaronyg** 2016-10-06 16:43 UTC
Labels: 0 - Icebox, bug, P2
